// FETCH
export const FETCH_CONTACTS_REQUEST = 'FETCH_CONTACTS_REQUEST'
export const FETCH_CONTACTS_SUCCESS = 'FETCH_CONTACTS_SUCCESS'
export const FETCH_CONTACTS_ERROR = 'FETCH_CONTACTS_ERROR'

// CREATE
export const CREATE_CONTACTS_REQUEST = 'CREATE_CONTACTS_REQUEST'
export const CREATE_CONTACTS_SUCCESS = 'CREATE_CONTACTS_SUCCESS'
export const CREATE_CONTACTS_ERROR = 'CREATE_CONTACTS_ERROR'

// UPDATE
export const UPDATE_CONTACTS_REQUEST = 'UPDATE_CONTACTS_REQUEST'
export const UPDATE_CONTACTS_SUCCESS = 'UPDATE_CONTACTS_SUCCESS'
export const UPDATE_CONTACTS_ERROR = 'UPDATE_CONTACTS_ERROR'

// DELETE
export const DELETE_CONTACTS_REQUEST = 'DELETE_CONTACTS_REQUEST'
export const DELETE_CONTACTS_SUCCESS = 'DELETE_CONTACTS_SUCCESS'
export const DELETE_CONTACTS_ERROR = 'DELETE_CONTACTS_ERROR'

export const SELECT_CONTACT = 'SELECT_CONTACT'
export const NEW_CONTACT = 'NEW_CONTACT'